[project]
name = "oblique-strategies-api"
version = "1.0.0"
description = "An API based on Brian Eno and Peter Schmidt's Oblique Strategies"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.116.1",
]

[dependency-groups]
dev = ["workers-py==1.1.4"]
