[project]
name = "oblique-strategies-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "webtypy==0.1.7",
]

[dependency-groups]
dev = [
    "isort>=6.0.1",
]
